configfile: "config/config.yaml"

MAGS, = glob_wildcards("data/mags/{mag}.fna")

include: "rules/checkm.smk"
include: "rules/carveme.smk"
include: "rules/memote.smk"
include: "rules/smetana.smk"
include: "rules/steadycom.smk"
include: "rules/micom.smk"

rule all:
    input:
        expand("results/checkm/{mag}/quality.tsv", mag=MAGS),
        expand("results/gems/{mag}.xml", mag=MAGS),
        expand("results/memote/{mag}/report.html", mag=MAGS),
        expand("results/memote/{mag}/score.json", mag=MAGS),
        "results/smetana/global.tsv",
        "results/smetana/detailed.tsv",
        "results/steadycom/abundances.tsv",
        "results/micom/exchange_fluxes.tsv"

        